// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQP0cKWRLdpzocP2fcqlJM6l_T21KVho',
    appId: '1:289124361110:ios:704e93773a2d4bd77073b7',
    messagingSenderId: '289124361110',
    projectId: 'nomo-b4485',
    storageBucket: 'nomo-b4485.firebasestorage.app',
    iosBundleId: 'com.example.nomoApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDFLEGeHvqLgD0hoJbHMwpYpN_w8adYu7U',
  appId: '1:289124361110:android:3d5bd88b655688cf7073b7',
  messagingSenderId: '289124361110',
  projectId: 'nomo-b4485',
  storageBucket: 'nomo-b4485.firebasestorage.app',
);

}
